### ISSUE TITLE
Add concurrency to the github actions

### ISSUE THREAD

**Issue by avinal** [openshift-pipelines/pipelines-service#89]
# Context

From [Github Actions Doc](https://docs.github.com/en/actions/using-jobs/using-concurrency)

> When a concurrent job or workflow is queued, if another job or workflow using the same concurrency group in the repository is in progress, the queued job or workflow will be pending. Any previously pending job or workflow in the concurrency group will be canceled. To also cancel any currently running job or workflow in the same concurrency group, specify cancel-in-progress: true.

# Proposal

To add concurrency to the GitHub Actions.

**Comment by bnallapeta** [comment]
@ramessesii2 PTAL.

**Comment by ramessesii2** [comment]
Hey @avinal, Thanks for the proposal.
You see our `workflows` have path based filtering as well. So, there are rare chances for now to get into a situation of multiple workflows in the same concurrency group. Still, if you think this is fit for the case. Please raise a PR with a clear description of how it will help, and the team will review it.

**Comment by fgiloux** [comment]
@avinal that's a good point but @ramessesii2 is also right that our workflows have very narrow scope due to
- path filtering
- no overlap on files triggering the workflows
- only triggered on main
The worst that can happen is that 2 PRs get merged around the same time modifying files in a way that produces no conflict. In that case we are not guaranteed that they are processed in the right order. The odds are very low.

**Comment by avinal** [comment]
I agree with you @ramessesii2 and @fgiloux, we can skip it I guess. Just wanted to bring up the point. 😃

**Comment by ramessesii2** [comment]
Thanks @avinal, closing it for now.
